// helpers/assignmentConstants.ts

import { AssignmentSettings } from "@/types/assignment";

export const DEF_SETTINGS: AssignmentSettings = {
  proctoring_settings: {
    browser_type: "*",
    main_camera_record: true,
    main_camera_upload: false,
    main_camera_blackhole: false,
    screen_share_record: true,
    screen_share_upload: false,
    screen_share_blackhole: false,
    second_camera_record: true,
    second_camera_upload: false,
    second_camera_blackhole: false,
    second_microphone_record: false,
    second_microphone_upload: false,
    second_microphone_blackhole: false,
    second_microphone_label:
      "RubleffTechnology_UMdesktop|USB PnP Sound Device|USB PnP Sound Device|USB Audio Device|\\\\.*USB Audio Device",
    check_env: true,
    displays_check: true,
    content_protect: false,
    fullscreen_mode: true,
    focus_detector: true,
    extension_detector: true,
    noise_detector: true,
    speech_detector: true,
    read_clipboard: false,
    id_verification: false,
    photo_head_identity: true,
    video_head_identity: false,
    head_tracking_client: true,
    head_tracking_server_post: false,
    head_tracking_server_realtime: false,
    noise_sensitivity: 10,
    head_x_sensitivity: 50,
    head_y_sensitivity: 40,
    head_depth_sensitivity: 12,
    head_center_area_size_x: 40,
    head_center_area_size_y: 30,
    head_position_confidence: 0.5,
    head_position_probability: 0.96,
    head_position_interval: 1200,
    head_compare_interval: 4000,
    head_compare_euclidean_distance: 0.5,
    face_landmarker: false,
    face_landmarker_interval: 700,
    face_landmarker_threshold: 0.5,
    face_landmarker_categories: {
      eyeLookInLeft: { action: "eye-left", score: 0.45 },
      eyeLookInRight: { action: "eye-right", score: 0.45 },
      eyeLookUpLeft: { action: "eye-up", score: 0.4 },
      eyeLookUpRight: { action: "eye-up", score: 0.4 },
      eyeLookDownLeft: { action: "eye-down", score: 0.4 },
      eyeLookDownRight: { action: "eye-down", score: 0.4 },
    },
    object_detect: false,
    object_detect_interval: 2000,
    object_detect_threshold: 0.5,
    object_detect_categories: {
      "cell phone": { action: "object-detected", score: 0.4, count: 1 },
      remote: { action: "object-detected", score: 0.4, count: 1 },
      laptop: { action: "object-detected", score: 0.4, count: 1 },
      person: { action: "head-many", score: 0.7, count: 2 },
    },
    noise_tolerance_frames: 3,
    noise_tolerance_seconds: 1500,
    speech_tolerance_seconds: 1500,
    speech_min_frames_count: 5,
    speech_pre_pad_frames: 10,
    speech_positive_threshold: 0.9,
    quite_frames_count: 30,
    mute_frames_count: 30,
    silent_tolerance_seconds: 1500,
    head_tolerance_seconds: 1500,
    focus_tolerance_seconds: 1500,
  },
  webinar_settings: {},
  component_settings: {
    all: {
      shuffle: false,
      per_student: 0,
      variant_split: false,
      conditions: [],
    },
  },
  scenario_settings: {
    conditions: [],
  },
  certificate: {
    issue_type: "auto-conditions",
    show_report: true,
  },
};
