export const mockQuiz = {
  status: "success",
  status_code: "0000",
  entities: {
    current_page: 1,
    data: [
      {
        id: 35100,
        name: "\u0442\u0435\u0441\u0442",
        description: "\u0442\u0435\u0441\u0442",
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFVrP8ZfJ7kBU7GFzuGgyvC69IaDIbfuywoja65sHFkmdkt7oxC0cFeM2x_sRPcT0zeB8&usqp=CAU",
        color: "0884EA",
      },
      {
        id: 35076,
        name: "\u041c\u0430\u0442\u0435\u043c\u0430\u0442\u0438\u043a\u0430",
        description: "7 - \u0441\u044b\u043d\u044b\u043f",
        image: null,
        color: "B22B0A",
      },
      {
        id: 35020,
        name: "Demo",
        description: null,
        image: null,
        color: "645085",
      },
    ],
    first_page_url: "http://api.oqylyq.kz/api/quiz?page=1",
    from: 1,
    last_page: 1,
    last_page_url: "http://api.oqylyq.kz/api/quiz?page=1",
    links: [
      {
        url: null,
        label: "&laquo; Previous",
        active: false,
      },
      {
        url: "http://api.oqylyq.kz/api/quiz?page=1",
        label: "1",
        active: true,
      },
      {
        url: null,
        label: "Next &raquo;",
        active: false,
      },
    ],
    next_page_url: null,
    path: "http://api.oqylyq.kz/api/quiz",
    per_page: 10,
    prev_page_url: null,
    to: 3,
    total: 3,
  },
};

export const mockData = {
  status: "success",
  status_code: "0000",
  entities: {
    id: 35108,
    owner_id: 2747436,
    name: "Столицы стран",
    description: "Тест на знание столиц",
    settings: [],
    components: [
      {
        id: 9605456,
        quiz_id: 35108,
        component_id: 377416,
        component_type: "FreeQuestionComponent",
        data: [],
        position: 0,
        settings: {
          group: "medium",
          variant: "first",
          score_penalty: "10",
          score_encouragement: "20",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 377416,
          owner_id: 2747436,
          component_type: "FreeQuestionComponent",
          question: "<p>Столица Казахстана?</p>",
          hint: "<p>Старое название</p>",
          feedback: null,
          description: null,
          is_multiple: null,
          created_at: "2025-09-11T09:39:23.000000Z",
          options: [
            {
              id: 1592596,
              free_question_id: 377416,
              type: null,
              answer: "<p>Астана</p>",
              feedback: null,
              percent: 100,
              is_true: 1,
              settings: [],
            },
            {
              id: 1592600,
              free_question_id: 377416,
              type: null,
              answer: "<p>Алматы</p>",
              feedback: null,
              percent: 0,
              is_true: null,
              settings: [],
            },
            {
              id: 1592604,
              free_question_id: 377416,
              type: null,
              answer: "<p>Нур-Султан</p>",
              feedback: null,
              percent: null,
              is_true: null,
              settings: [],
            },
          ],
          attempts: null,
          settings: {
            group: "medium",
            variant: "first",
            score_penalty: "10",
            score_encouragement: "20",
          },
          updated_at: "2025-09-11T09:39:23.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
      {
        id: 9605460,
        quiz_id: 35108,
        component_id: 828328,
        component_type: "OpenQuestionComponent",
        data: [],
        position: 1,
        settings: {
          group: "easy",
          variant: "second",
          attachments: false,
          score_penalty: "5",
          antiplagiarism: false,
          score_encouragement: "10",
        },
        component: {
          _attempts_showed: false,
          _answers_showed: false,
          id: 828328,
          owner_id: 2747436,
          component_type: "OpenQuestionComponent",
          question: "<p>Столица Италии?</p>",
          answer: "<p>Рим</p>",
          hint: "<p>Пицца паста</p>",
          feedback: null,
          description: null,
          attempt: null,
          settings: {
            group: "easy",
            variant: "second",
            attachments: false,
            score_penalty: "5",
            antiplagiarism: false,
            score_encouragement: "10",
          },
          created_at: "2025-09-11T09:40:02.000000Z",
          updated_at: "2025-09-11T09:40:02.000000Z",
        },
      },
    ],
  },
};
